export interface Course {
  code: string;
  name: string;
  prereq: string;
  credits: number;
  level: string;
  semester: string;
  specialization: string;
}

export const SPECIALIZATIONS = [
  "Agricultural Engineering",
  "Civil Engineering",
  "Computer Engineering",
  "Electrical Engineering",
  "Electronics and Communication Engineering",
  "Mechanical Engineering",
  "Mechatronics Engineering",
  "Textile and Clothing Engineering",
];

// Simplified/Cleaned version of the extracted data
export const COURSE_DATA: Course[] = [
  // Agricultural Engineering
  {
    code: "AGM3203",
    name: "Communication skills",
    prereq: "None",
    credits: 2,
    level: "3",
    semester: "1",
    specialization: "Agricultural Engineering",
  },
  {
    code: "CVB3310",
    name: "Mechanics and Materials",
    prereq: "None",
    credits: 3,
    level: "3",
    semester: "1",
    specialization: "Agricultural Engineering",
  },
  {
    code: "DMB3301",
    name: "Thermo - Fluids",
    prereq: "None",
    credits: 3,
    level: "3",
    semester: "1",
    specialization: "Agricultural Engineering",
  },
  {
    code: "DMS3203",
    name: "Workshop Practice",
    prereq: "None",
    credits: 1,
    level: "3",
    semester: "1",
    specialization: "Agricultural Engineering",
  },
  {
    code: "DMS3205",
    name: "Engineering Graphics",
    prereq: "None",
    credits: 2,
    level: "3",
    semester: "1",
    specialization: "Agricultural Engineering",
  },
  {
    code: "EEB3210",
    name: "Theory of Electricity",
    prereq: "None",
    credits: 2,
    level: "3",
    semester: "1",
    specialization: "Agricultural Engineering",
  },
  {
    code: "EEK3217",
    name: "Programming Fundamentals",
    prereq: "None",
    credits: 2,
    level: "3",
    semester: "1",
    specialization: "Agricultural Engineering",
  },
  {
    code: "MHZ3310",
    name: "Calculus I",
    prereq: "None",
    credits: 3,
    level: "3",
    semester: "1",
    specialization: "Agricultural Engineering",
  },
  {
    code: "AGB3101",
    name: "Essentials of Life and Earth Systems",
    prereq: "None",
    credits: 1,
    level: "3",
    semester: "2",
    specialization: "Agricultural Engineering",
  },
  {
    code: "AGS3201",
    name: "Basic Biology",
    prereq: "None",
    credits: 2,
    level: "3",
    semester: "2",
    specialization: "Agricultural Engineering",
  },
  {
    code: "DMB3202",
    name: "Measurements in Engineering",
    prereq: "None",
    credits: 2,
    level: "3",
    semester: "2",
    specialization: "Agricultural Engineering",
  },
  {
    code: "EEK3218",
    name: "Software Development for Engineers",
    prereq: "EEK3217(CR)",
    credits: 2,
    level: "3",
    semester: "2",
    specialization: "Agricultural Engineering",
  },
  {
    code: "MHZ3311",
    name: "Differential Equations",
    prereq: "MHZ3310(CR)",
    credits: 3,
    level: "3",
    semester: "2",
    specialization: "Agricultural Engineering",
  },
  {
    code: "MHZ3212",
    name: "Linear Algebra",
    prereq: "None",
    credits: 2,
    level: "3",
    semester: "2",
    specialization: "Agricultural Engineering",
  },

  // Civil Engineering
  {
    code: "AGM3203",
    name: "Communication Skills",
    prereq: "None",
    credits: 2,
    level: "3",
    semester: "1",
    specialization: "Civil Engineering",
  },
  {
    code: "CVB3310",
    name: "Mechanics and Materials",
    prereq: "None",
    credits: 3,
    level: "3",
    semester: "1",
    specialization: "Civil Engineering",
  },
  {
    code: "DMB3301",
    name: "Heat and Fluid",
    prereq: "None",
    credits: 3,
    level: "3",
    semester: "1",
    specialization: "Civil Engineering",
  },
  {
    code: "DMS3205",
    name: "Engineering Graphics",
    prereq: "None",
    credits: 2,
    level: "3",
    semester: "1",
    specialization: "Civil Engineering",
  },
  {
    code: "MHZ3310",
    name: "Calculus I",
    prereq: "None",
    credits: 3,
    level: "3",
    semester: "1",
    specialization: "Civil Engineering",
  },
  {
    code: "CVS3340",
    name: "Fundamentals of Hydrology and Hydraulics",
    prereq: "DMB3301(CR)",
    credits: 3,
    level: "3",
    semester: "2",
    specialization: "Civil Engineering",
  },
  {
    code: "CVS3242",
    name: "Strength of Materials",
    prereq: "None",
    credits: 2,
    level: "3",
    semester: "2",
    specialization: "Civil Engineering",
  },
  {
    code: "CVS4241",
    name: "Structural Analysis I",
    prereq: "CVS3242(CA)",
    credits: 2,
    level: "4",
    semester: "3",
    specialization: "Civil Engineering",
  },
  {
    code: "CVS4243",
    name: "Soil Mechanics",
    prereq: "CVS3340(CA), CVS3242(CA)",
    credits: 2,
    level: "4",
    semester: "3",
    specialization: "Civil Engineering",
  },
  {
    code: "CVS5245",
    name: "Design of Concrete Structures",
    prereq: "CVS3242(P), CVS4245(CA)",
    credits: 2,
    level: "5",
    semester: "5",
    specialization: "Civil Engineering",
  },
  {
    code: "CVS5344",
    name: "Geotechnical Engineering",
    prereq: "CVS4243(CA)",
    credits: 3,
    level: "5",
    semester: "6",
    specialization: "Civil Engineering",
  },
  {
    code: "CVY6385",
    name: "Comprehensive Design Project",
    prereq: "LTE34TI(P), CVS5242(P), CVS5245(P)",
    credits: 5,
    level: "6",
    semester: "7",
    specialization: "Civil Engineering",
  },

  // Computer Engineering
  {
    code: "EEK3217",
    name: "Programming Fundamentals",
    prereq: "None",
    credits: 2,
    level: "3",
    semester: "1",
    specialization: "Computer Engineering",
  },
  {
    code: "EEK3218",
    name: "Software Development for Engineers",
    prereq: "EEK3217(CR)",
    credits: 2,
    level: "3",
    semester: "2",
    specialization: "Computer Engineering",
  },
  {
    code: "EES4235",
    name: "Data Structures and Algorithms",
    prereq: "EEK3218(CA), MHZ4313(CR)",
    credits: 3,
    level: "4",
    semester: "3",
    specialization: "Computer Engineering",
  },
  {
    code: "EES4436",
    name: "Microprocessors and Interfacing",
    prereq: "EEK3218(CA)",
    credits: 2,
    level: "4",
    semester: "3",
    specialization: "Computer Engineering",
  },
  {
    code: "EES5326",
    name: "Digital Electronic Design",
    prereq: "EES4436(CA)",
    credits: 3,
    level: "5",
    semester: "5",
    specialization: "Computer Engineering",
  },
  {
    code: "EES5334",
    name: "Data Communications and Networks",
    prereq: "EES3236(P)",
    credits: 3,
    level: "5",
    semester: "6",
    specialization: "Computer Engineering",
  },
  {
    code: "EEY6401",
    name: "System Design in Groups",
    prereq: "EES4230(P), EES5317(P)",
    credits: 3,
    level: "6",
    semester: "7",
    specialization: "Computer Engineering",
  },

  // Electrical Engineering
  {
    code: "EEB3210",
    name: "Theory of Electricity",
    prereq: "None",
    credits: 2,
    level: "3",
    semester: "1",
    specialization: "Electrical Engineering",
  },
  {
    code: "EES3330",
    name: "Introduction to Electrical and Electronic",
    prereq: "EEB3210(CR)",
    credits: 3,
    level: "3",
    semester: "2",
    specialization: "Electrical Engineering",
  },
  {
    code: "EES4222",
    name: "Power Systems and Electrical Machines",
    prereq: "EES3330(CA)",
    credits: 2,
    level: "4",
    semester: "3",
    specialization: "Electrical Engineering",
  },
  {
    code: "EES5316",
    name: "Power Electronics",
    prereq: "EES4230(CA)",
    credits: 3,
    level: "5",
    semester: "5",
    specialization: "Electrical Engineering",
  },
  {
    code: "EES5328",
    name: "Electrical Machines and Drives",
    prereq: "EES4328(CA)",
    credits: 3,
    level: "5",
    semester: "6",
    specialization: "Electrical Engineering",
  },
  {
    code: "EES6222",
    name: "Modern Power Systems",
    prereq: "EES4332(P)",
    credits: 2,
    level: "6",
    semester: "7",
    specialization: "Electrical Engineering",
  },

  // Electronics and Communication Engineering
  {
    code: "EES4333",
    name: "Communications",
    prereq: "EES3236(CA)",
    credits: 3,
    level: "4",
    semester: "4",
    specialization: "Electronics and Communication Engineering",
  },
  {
    code: "EES5333",
    name: "Communication Theory and Systems",
    prereq: "EES4333(CA)",
    credits: 3,
    level: "5",
    semester: "5",
    specialization: "Electronics and Communication Engineering",
  },
  {
    code: "EES6211",
    name: "Electromagnetism and Wave Propagation",
    prereq: "MHZ4313(CA)",
    credits: 2,
    level: "5",
    semester: "5",
    specialization: "Electronics and Communication Engineering",
  },
  {
    code: "EES6333",
    name: "Wireless Communications",
    prereq: "EES5333(CR)",
    credits: 3,
    level: "5",
    semester: "6",
    specialization: "Electronics and Communication Engineering",
  },
  {
    code: "EES6213",
    name: "Microwave Engineering",
    prereq: "EES6211(CR)",
    credits: 2,
    level: "6",
    semester: "8",
    specialization: "Electronics and Communication Engineering",
  },

  // Mechanical Engineering
  {
    code: "DMB3301",
    name: "Thermo-Fluids",
    prereq: "None",
    credits: 3,
    level: "3",
    semester: "1",
    specialization: "Mechanical Engineering",
  },
  {
    code: "DMS3204",
    name: "Engineering Mechanics I",
    prereq: "CVB3310(CR)",
    credits: 2,
    level: "3",
    semester: "2",
    specialization: "Mechanical Engineering",
  },
  {
    code: "DMS4201",
    name: "Applied Thermodynamics I",
    prereq: "DMB3301(CA)",
    credits: 2,
    level: "4",
    semester: "3",
    specialization: "Mechanical Engineering",
  },
  {
    code: "DMS5406",
    name: "Design of Machine Elements",
    prereq: "DMS3204(P), DMS4205(CA)",
    credits: 4,
    level: "5",
    semester: "5",
    specialization: "Mechanical Engineering",
  },
  {
    code: "DMS5411",
    name: "Mechanical Engineering Design",
    prereq: "DMS5406(CR)",
    credits: 4,
    level: "5",
    semester: "6",
    specialization: "Mechanical Engineering",
  },
  {
    code: "DMS6211",
    name: "Thermal Power Technologies",
    prereq: "DMS5203(CA)",
    credits: 2,
    level: "6",
    semester: "7",
    specialization: "Mechanical Engineering",
  },

  // Mechatronics Engineering
  {
    code: "DMS4203",
    name: "Mechatronics systems",
    prereq: "DMB3202(CA), DMS3207(CA)",
    credits: 2,
    level: "4",
    semester: "3",
    specialization: "Mechatronics Engineering",
  },
  {
    code: "DMS4210",
    name: "Sensors and Instrumentation",
    prereq: "DMS3207(CA)",
    credits: 2,
    level: "4",
    semester: "3",
    specialization: "Mechatronics Engineering",
  },
  {
    code: "DMS5217",
    name: "Mechatronics Product Design I",
    prereq: "DMS3207(CA)",
    credits: 2,
    level: "5",
    semester: "5",
    specialization: "Mechatronics Engineering",
  },
  {
    code: "DMS6203",
    name: "Robot Manipulation and Control",
    prereq: "DMS5201(CA)",
    credits: 2,
    level: "6",
    semester: "7",
    specialization: "Mechatronics Engineering",
  },
  {
    code: "DMS6207",
    name: "Modern Control Systems",
    prereq: "DMS5210(CA)",
    credits: 2,
    level: "6",
    semester: "7",
    specialization: "Mechatronics Engineering",
  },

  // Textile and Clothing Engineering
  {
    code: "TAS3310",
    name: "Fiber Science & Technology",
    prereq: "None",
    credits: 3,
    level: "3",
    semester: "2",
    specialization: "Textile and Clothing Engineering",
  },
  {
    code: "TAS4311",
    name: "Woven Fabric Technology",
    prereq: "TAS3310(CA)",
    credits: 3,
    level: "4",
    semester: "3",
    specialization: "Textile and Clothing Engineering",
  },
  {
    code: "TAS4413",
    name: "Garment Manufacture",
    prereq: "TAS3317(CA)",
    credits: 4,
    level: "4",
    semester: "4",
    specialization: "Textile and Clothing Engineering",
  },
  {
    code: "TAS5211",
    name: "Textile Printing and Finishing",
    prereq: "TAS5210(CR)",
    credits: 2,
    level: "5",
    semester: "6",
    specialization: "Textile and Clothing Engineering",
  },
];
