export type ButtonConfig = {
  label: string;
  variant: "default" | "outline" | "ghost" | "link" | "secondary" | "destructive";
  size: "default" | "sm" | "lg" | "icon";
  radius: "none" | "sm" | "md" | "lg" | "xl" | "2xl" | "full";
  fullWidth: boolean;
  hasShadow: boolean;
  uppercase: boolean;
  hasIcon: "none" | "leading" | "trailing";
  isDisabled: boolean;
};

export type PresetItem = {
  id: string;
  name: string;
  description: string;
  tags: string[];
  config: ButtonConfig;
  customClasses?: string;
  isFeatured?: boolean;
};

export const DEFAULT_CONFIG: ButtonConfig = {
  label: "Click Me",
  variant: "default",
  size: "default",
  radius: "md",
  fullWidth: false,
  hasShadow: false,
  uppercase: false,
  hasIcon: "none",
  isDisabled: false,
};

export const PRESET_LIBRARY: PresetItem[] = [
  {
    id: "classic-solid",
    name: "Classic Solid",
    description: "Standard primary button style.",
    tags: ["minimal", "clean"],
    config: { ...DEFAULT_CONFIG, variant: "default" },
    isFeatured: true,
  },
  {
    id: "soft-secondary",
    name: "Soft Secondary",
    description: "Subtle secondary background.",
    tags: ["minimal", "clean"],
    config: { ...DEFAULT_CONFIG, variant: "secondary" },
  },
  {
    id: "clean-outline",
    name: "Clean Outline",
    description: "Bordered button with transparent background.",
    tags: ["minimal", "clean"],
    config: { ...DEFAULT_CONFIG, variant: "outline" },
  },
  {
    id: "subtle-ghost",
    name: "Subtle Ghost",
    description: "No border or background until hover.",
    tags: ["minimal", "clean"],
    config: { ...DEFAULT_CONFIG, variant: "ghost" },
  },
  {
    id: "destructive-action",
    name: "Danger Zone",
    description: "Emphasis on destructive actions.",
    tags: ["minimal", "brutalist"],
    config: { ...DEFAULT_CONFIG, variant: "destructive" },
  },
  {
    id: "heavy-border",
    name: "Thick Outline",
    description: "Bold border for high contrast.",
    tags: ["minimal", "brutalist"],
    config: { ...DEFAULT_CONFIG, variant: "outline" },
    customClasses: "border-2 border-primary",
  },
  {
    id: "rounded-icon",
    name: "Circle Icon",
    description: "Perfectly circular icon button.",
    tags: ["minimal", "icon"],
    config: { ...DEFAULT_CONFIG, size: "icon", radius: "full" },
  },
  {
    id: "wide-pill",
    name: "Wide Pill",
    description: "Extra wide call to action.",
    tags: ["minimal", "clean"],
    config: { ...DEFAULT_CONFIG, radius: "full", size: "lg" },
  },
  {
    id: "square-mono",
    name: "Sharp Square",
    description: "No rounding for a brutalist feel.",
    tags: ["minimal", "brutalist"],
    config: { ...DEFAULT_CONFIG, radius: "none" },
  },
  {
    id: "extra-small",
    name: "Tiny Button",
    description: "Compact size for tight spaces.",
    tags: ["minimal", "clean"],
    config: { ...DEFAULT_CONFIG, size: "sm" },
  },
  {
    id: "caps-link",
    name: "Uppercase Link",
    description: "All caps link button.",
    tags: ["minimal", "clean"],
    config: { ...DEFAULT_CONFIG, variant: "link", uppercase: true },
  },
  {
    id: "shadow-lg",
    name: "Elevated Button",
    description: "Strong shadow for depth.",
    tags: ["minimal", "clean"],
    config: { ...DEFAULT_CONFIG, hasShadow: true },
    customClasses: "shadow-xl",
  },
  {
    id: "full-width-sm",
    name: "Full Width Mini",
    description: "Full width but small height.",
    tags: ["minimal", "clean"],
    config: { ...DEFAULT_CONFIG, fullWidth: true, size: "sm" },
  },
  {
    id: "dashed-outline",
    name: "Dashed Border",
    description: "Dashed border style.",
    tags: ["minimal", "retro"],
    config: { ...DEFAULT_CONFIG, variant: "outline" },
    customClasses: "border-dashed border-2",
  },
  {
    id: "semi-transparent",
    name: "Muted Fill",
    description: "Light primary background.",
    tags: ["minimal", "glass"],
    config: { ...DEFAULT_CONFIG, variant: "ghost" },
    customClasses: "bg-primary/5 hover:bg-primary/15",
  },
  {
    id: "tracking-tight",
    name: "Tight Text",
    description: "Condensed letter spacing.",
    tags: ["minimal"],
    config: { ...DEFAULT_CONFIG },
    customClasses: "tracking-tighter font-bold",
  },
  {
    id: "bold-italic",
    name: "Emphasis Text",
    description: "Bold and italic label.",
    tags: ["minimal"],
    config: { ...DEFAULT_CONFIG },
    customClasses: "font-black italic",
  },
  {
    id: "double-ring",
    name: "Double Ring",
    description: "Border with internal ring.",
    tags: ["minimal", "retro"],
    config: { ...DEFAULT_CONFIG, variant: "outline" },
    customClasses: "ring-2 ring-primary ring-offset-2",
  },
  {
    id: "gradient-text",
    name: "Primary Text",
    description: "Emphasis on text color.",
    tags: ["minimal"],
    config: { ...DEFAULT_CONFIG, variant: "ghost" },
    customClasses: "text-primary font-bold",
  },
  {
    id: "glass-dark",
    name: "Glass Dark",
    description: "Dark glass effect.",
    tags: ["glass"],
    config: { ...DEFAULT_CONFIG, variant: "ghost" },
    customClasses: "bg-black/20 backdrop-blur-md border border-white/10 text-white",
  },
  {
    id: "glass-light",
    name: "Glass Light",
    description: "Light glass effect.",
    tags: ["glass"],
    config: { ...DEFAULT_CONFIG, variant: "ghost" },
    customClasses: "bg-white/20 backdrop-blur-md border border-black/10 text-black",
  },
  {
    id: "neon-border",
    name: "Neon Border",
    description: "Glowing border only.",
    tags: ["neon"],
    config: { ...DEFAULT_CONFIG, variant: "outline" },
    customClasses: "border-primary shadow-[0_0_10px_rgba(var(--primary),0.5)]",
  },
  {
    id: "soft-pill",
    name: "Soft Pill",
    description: "Pill shape with soft color.",
    tags: ["minimal", "clean"],
    config: { ...DEFAULT_CONFIG, variant: "secondary", radius: "full" },
  },
  {
    id: "underlined-ghost",
    name: "Underline Ghost",
    description: "Ghost style with underline.",
    tags: ["minimal"],
    config: { ...DEFAULT_CONFIG, variant: "ghost" },
    customClasses: "underline",
  },
  {
    id: "heavy-shadow-pill",
    name: "Floating Pill",
    description: "Pill with massive shadow.",
    tags: ["minimal", "clean"],
    config: { ...DEFAULT_CONFIG, radius: "full", hasShadow: true },
    customClasses: "shadow-2xl translate-y-[-2px]",
  },
  {
    id: "mono-outline",
    name: "Mono Outline",
    description: "Black/White outline.",
    tags: ["minimal", "brutalist"],
    config: { ...DEFAULT_CONFIG, variant: "outline" },
    customClasses: "border-foreground text-foreground",
  }
];

export const RECIPE_LIBRARY: PresetItem[] = [
  {
    id: "primary-cta",
    name: "Primary CTA",
    description: "High emphasis call-to-action.",
    tags: ["minimal", "clean"],
    config: { 
      ...DEFAULT_CONFIG, 
      label: "Get Started", 
      size: "lg", 
      radius: "full", 
      hasShadow: true,
      hasIcon: "trailing" 
    },
    isFeatured: true,
  },
  {
    id: "soft-accent",
    name: "Soft Accent",
    description: "Accent-tinted button using opacity.",
    tags: ["minimal", "clean", "glass"],
    config: { 
      ...DEFAULT_CONFIG, 
      variant: "ghost",
      label: "View More",
    },
    customClasses: "bg-primary/10 text-primary hover:bg-primary/20 hover:text-primary border-none shadow-none",
    isFeatured: true,
  },
  {
    id: "3d-pressable",
    name: "3D Pressable",
    description: "Raised button that sinks when clicked.",
    tags: ["3d", "retro"],
    config: { ...DEFAULT_CONFIG, radius: "lg" },
    customClasses: "bg-primary text-primary-foreground border-b-4 border-primary/70 active:border-b-0 active:translate-y-1 transition-all duration-75",
    isFeatured: true,
  },
  {
    id: "duolingo-style",
    name: "Soft 3D",
    description: "Friendly, puffy Duolingo-like feel.",
    tags: ["3d", "clean"],
    config: { ...DEFAULT_CONFIG, radius: "2xl", uppercase: true },
    customClasses: "bg-primary text-primary-foreground border-b-[6px] border-primary/50 active:border-b-0 active:translate-y-[2px] transition-all font-black",
    isFeatured: true,
  },
  {
    id: "neon-glow",
    name: "Neon Glow",
    description: "Cyberpunk-inspired outer glow.",
    tags: ["neon", "cyber"],
    config: { ...DEFAULT_CONFIG, variant: "default", radius: "md" },
    customClasses: "shadow-[0_0_15px_rgba(var(--primary),0.6)] hover:shadow-[0_0_25px_rgba(var(--primary),0.8)] transition-shadow",
    isFeatured: true,
  },
  {
    id: "glassmorphism",
    name: "Glassmorphism",
    description: "Frosted glass effect with blur.",
    tags: ["glass", "modern"],
    config: { ...DEFAULT_CONFIG, variant: "ghost", radius: "xl" },
    customClasses: "bg-primary/10 backdrop-blur-md border border-primary/20 hover:bg-primary/20 transition-all shadow-xl",
    isFeatured: true,
  },
  {
    id: "brutalist-card",
    name: "Brutalist Pop",
    description: "Thick borders and offset shadows.",
    tags: ["brutalist", "retro"],
    config: { ...DEFAULT_CONFIG, radius: "none" },
    customClasses: "border-4 border-foreground shadow-[8px_8px_0_0_rgba(var(--primary),1)] active:translate-x-1 active:translate-y-1 active:shadow-none transition-all font-black",
    isFeatured: true,
  },
  {
    id: "shimmer-effect",
    name: "Shimmer Slide",
    description: "Animated background fill on hover.",
    tags: ["animated", "clean"],
    config: { ...DEFAULT_CONFIG, variant: "outline", radius: "md" },
    customClasses: "relative overflow-hidden group hover:text-primary-foreground transition-colors duration-300 before:absolute before:inset-0 before:bg-primary before:translate-x-[-100%] hover:before:translate-x-0 before:transition-transform before:duration-300 before:-z-10",
  },
  {
    id: "inset-shadow",
    name: "Sunken Inset",
    description: "Pressed-in feel using internal shadows.",
    tags: ["neumorphism", "3d"],
    config: { ...DEFAULT_CONFIG, variant: "ghost", radius: "lg" },
    customClasses: "shadow-[inset_4px_4px_8px_rgba(0,0,0,0.2),inset_-4px_-4px_8px_rgba(255,255,255,0.1)] bg-muted/50",
  },
  {
    id: "claymorphism",
    name: "Clay Pill",
    description: "Soft, voluminous 3D effect.",
    tags: ["3d", "modern"],
    config: { ...DEFAULT_CONFIG, radius: "full" },
    customClasses: "bg-primary text-primary-foreground shadow-[8px_8px_16px_rgba(0,0,0,0.1),inset_-8px_-8px_12px_rgba(0,0,0,0.1),inset_8px_8px_12px_rgba(255,255,255,0.2)]",
  },
  {
    id: "bento-accent",
    name: "Bento Accent",
    description: "Minimalist bento-style design.",
    tags: ["minimal", "clean"],
    config: { ...DEFAULT_CONFIG, radius: "xl", variant: "secondary" },
    customClasses: "hover:scale-[1.02] active:scale-[0.98] transition-transform",
  },
  {
    id: "pixel-retro",
    name: "Pixel Retro",
    description: "Sharp corners and blocky shadow.",
    tags: ["retro", "brutalist"],
    config: { ...DEFAULT_CONFIG, radius: "none" },
    customClasses: "border-2 border-primary shadow-[4px_4px_0_0_var(--primary)] active:shadow-none active:translate-x-1 active:translate-y-1 transition-all",
  },
  {
    id: "spotlight-hover",
    name: "Spotlight",
    description: "Subtle glow follows the cursor vibe.",
    tags: ["animated", "neon"],
    config: { ...DEFAULT_CONFIG, variant: "outline", radius: "full" },
    customClasses: "hover:bg-primary/5 hover:border-primary hover:shadow-[0_0_20px_rgba(var(--primary),0.3)] transition-all",
  },
  {
    id: "magnetic-pill",
    name: "Magnetic Pill",
    description: "Pill button with animated border.",
    tags: ["animated", "clean"],
    config: { ...DEFAULT_CONFIG, radius: "full" },
    customClasses: "border-2 border-transparent bg-primary text-primary-foreground hover:border-primary hover:bg-transparent hover:text-primary transition-all duration-500",
  },
  {
    id: "glass-neon",
    name: "Glass Neon",
    description: "Glassy fill with neon outline.",
    tags: ["glass", "neon"],
    config: { ...DEFAULT_CONFIG, radius: "lg" },
    customClasses: "bg-primary/20 backdrop-blur-lg border-2 border-primary shadow-[0_0_15px_rgba(var(--primary),0.4)] text-primary font-bold",
  },
  {
    id: "floating-aura",
    name: "Floating Aura",
    description: "Soft ambient glow beneath button.",
    tags: ["neon", "modern"],
    config: { ...DEFAULT_CONFIG, variant: "default", radius: "full" },
    customClasses: "relative after:absolute after:inset-0 after:bg-primary/40 after:blur-xl after:-z-10 hover:after:opacity-100 after:opacity-50 after:transition-opacity",
  },
  {
    id: "cyber-outline",
    name: "Cyber Outline",
    description: "Dual-layer border effect.",
    tags: ["neon", "cyber"],
    config: { ...DEFAULT_CONFIG, variant: "outline", radius: "none" },
    customClasses: "border-primary outline outline-2 outline-primary/30 outline-offset-4 hover:outline-offset-2 transition-all",
  },
  {
    id: "skeuomorphic-flat",
    name: "Skeuo-Flat",
    description: "Subtle top highlight for depth.",
    tags: ["3d", "clean"],
    config: { ...DEFAULT_CONFIG, variant: "default", radius: "md" },
    customClasses: "shadow-[inset_0_1px_0_0_rgba(255,255,255,0.4),0_2px_4px_rgba(0,0,0,0.2)]",
  },
  {
    id: "ghost-underline-draw",
    name: "Underline Draw",
    description: "Underline expands from center.",
    tags: ["animated", "minimal"],
    config: { ...DEFAULT_CONFIG, variant: "ghost" },
    customClasses: "relative after:absolute after:bottom-1 after:left-1/2 after:w-0 after:h-[2px] after:bg-primary after:-translate-x-1/2 hover:after:w-3/4 after:transition-all duration-300",
  },
  {
    id: "split-3d",
    name: "Split 3D",
    description: "Two-tone 3D side effect.",
    tags: ["3d", "retro"],
    config: { ...DEFAULT_CONFIG, radius: "sm" },
    customClasses: "bg-primary text-primary-foreground shadow-[2px_2px_0_0_rgba(var(--primary),0.5),4px_4px_0_0_rgba(var(--primary),0.3)] active:shadow-none active:translate-x-1 active:translate-y-1 transition-all",
  },
  {
    id: "rainbow-border",
    name: "Accent Flow",
    description: "Subtle animated border tint.",
    tags: ["animated", "neon"],
    config: { ...DEFAULT_CONFIG, variant: "outline", radius: "full" },
    customClasses: "border-primary/20 hover:border-primary transition-colors duration-1000",
  },
  {
    id: "neu-raised",
    name: "Neu Raised",
    description: "Classic neumorphic raised effect.",
    tags: ["neumorphism"],
    config: { ...DEFAULT_CONFIG, radius: "2xl", variant: "ghost" },
    customClasses: "bg-muted shadow-[8px_8px_16px_rgba(0,0,0,0.1),-8px_-8px_16px_rgba(255,255,255,0.8)] dark:shadow-[8px_8px_16px_rgba(0,0,0,0.4),-4px_-4px_12px_rgba(255,255,255,0.05)]",
  },
  {
    id: "clay-puffy",
    name: "Clay Puffy",
    description: "Soft clay style with highlight.",
    tags: ["3d", "modern"],
    config: { ...DEFAULT_CONFIG, radius: "xl" },
    customClasses: "bg-primary text-primary-foreground shadow-[0_10px_20px_rgba(0,0,0,0.1),inset_0_-5px_0_rgba(0,0,0,0.1),inset_0_5px_0_rgba(255,255,255,0.2)]",
  },
  {
    id: "minimal-stealth",
    name: "Stealth Mode",
    description: "Barely visible until interaction.",
    tags: ["minimal"],
    config: { ...DEFAULT_CONFIG, variant: "ghost" },
    customClasses: "opacity-40 hover:opacity-100 transition-opacity",
  },
  {
    id: "thick-brutalist-pill",
    name: "Bold Pill",
    description: "Pill shape with heavy border.",
    tags: ["brutalist", "minimal"],
    config: { ...DEFAULT_CONFIG, radius: "full" },
    customClasses: "border-4 border-foreground font-black hover:bg-foreground hover:text-background transition-colors",
  },
  {
    id: "glass-shimmer",
    name: "Glass Shimmer",
    description: "Shimmering glass effect.",
    tags: ["glass", "animated"],
    config: { ...DEFAULT_CONFIG, radius: "lg" },
    customClasses: "bg-white/10 backdrop-blur-md border border-white/20 overflow-hidden relative before:absolute before:inset-0 before:-translate-x-full before:bg-gradient-to-r before:from-transparent before:via-white/20 before:to-transparent hover:before:translate-x-full before:transition-transform before:duration-700",
  },
  {
    id: "neon-pill-glow",
    name: "Neon Pill",
    description: "Pill button with strong neon aura.",
    tags: ["neon", "modern"],
    config: { ...DEFAULT_CONFIG, radius: "full", variant: "default" },
    customClasses: "shadow-[0_0_20px_rgba(var(--primary),0.4)] ring-2 ring-primary/50",
  }
];
